/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CPUSchedulersSimulator;

import org.junit.Test;
import static org.junit.Assert.*;

public class FakeClassTest {
    @Test 
    public void testSomeLibraryMethod() {
        FakeClass classUnderTest = new FakeClass();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someClassMethod());
    }
}
