/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CPUSchedulersSimulator;

import org.junit.Test;
import static org.junit.Assert.*;

public class FakeClassTest {
    @Test 
    public void testSomeLibraryMethod() {
        FakeClass classUnderTest = new FakeClass();
        
        // use assert function to compare results
        // assertEquals("expected string from the test", "actual value");
        
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someClassMethod());
    }
}
